### ISSUE TITLE
Pawn promotion and check/checkmate

### ISSUE THREAD

**Issue by Meelo** [Meelo/NALCG#33]
Pawn promotion animation is skipped when promotion causes check. Afterwards, the promoted pawn will still look like a pawn, but moves like a queen, rook, knight or bishop.

**Comment by Dzarg** [comment]
Fixed. There were also problems with other special moves (castle and en passant).

**Comment by Meelo** [comment]
re-opened, since checkmate still doesn't work, it actually is more critical now, since this causes game to segfault.

**Comment by Dzarg** [comment]
Checkmate now works with promotion, but still behaves strangely with en passant and castle. Though at least the game doesn't crash in those anymore.

**Comment by Dzarg** [comment]
Works now with en passant, but still strangely with castle.
